"""Pace, loudness summary, outputs (timings JSON, TS module) and the printed table for vo_build.py."""
import argparse
import json
import statistics

import _voice_text as text_tools
from _voice_qa_checks import SYLLABLE_LANGUAGES, Thresholds, expected_seconds

Word = dict[str, str | float]


def pace(spoken: list[Word], duration: float, language: str | None, args: argparse.Namespace) -> dict:
    text = " ".join(str(word["text"]) for word in spoken)
    span = float(spoken[-1]["end"]) - float(spoken[0]["start"]) if spoken else 0.0
    wpm = round(len(spoken) / span * 60, 1) if span > 0 else None
    label = "n/a (<6 words)" if len(spoken) < 6 or wpm is None else "fast" if wpm > args.fast else "slow" if wpm < args.slow else "ok"
    syllables = text_tools.syllables(text, language) if language in SYLLABLE_LANGUAGES else None
    expected, basis = expected_seconds(text, language, Thresholds(sps=args.sps)) if spoken else (None, "")
    return {
        "wpm": wpm,
        "pace": label,
        "language": language,
        "wordsPerSecond": round(len(spoken) / span, 2) if span > 0 else None,
        "syllables": syllables,
        "syllablesPerSecond": round(syllables / span, 2) if syllables and span > 0 else None,
        "expectedDuration": round(expected, 2) if expected else None,
        "expectedBasis": basis,
        "durationRatio": round(duration / expected, 2) if expected else None,
    }


def loudness_summary(lines: list[dict], target: float | None, quiet_delta: float) -> dict:
    inputs = [line["loudness"]["input_lufs"] for line in lines if line["loudness"]["input_lufs"] is not None]
    outputs = [line["loudness"]["output_lufs"] for line in lines if line["loudness"]["output_lufs"] is not None]
    peaks = [line["loudness"]["output_true_peak"] for line in lines if line["loudness"]["output_true_peak"] is not None]
    median = statistics.median(inputs) if inputs else None
    quiet = [line["id"] for line in lines
             if median is not None and line["loudness"]["input_lufs"] is not None and median - line["loudness"]["input_lufs"] >= quiet_delta]
    return {
        "target_lufs": target,
        "input_median_lufs": round(median, 1) if median is not None else None,
        "output_spread_lu": round(max(outputs) - min(outputs), 2) if outputs else None,
        "max_true_peak": max(peaks, default=None),
        "quiet_at_source": quiet,
    }


def write_outputs(lines: list[dict], summary: dict, args: argparse.Namespace, ts_fields: tuple[str, ...]) -> None:
    keyed = {line["id"]: {field: line[field] for field in ts_fields} for line in lines}
    args.json.parent.mkdir(parents=True, exist_ok=True)
    payload = {"lines": keyed, "loudness": summary, "report": lines}
    args.json.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n")
    print(f"wrote {args.json}")
    if not args.ts:
        return
    args.ts.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(keyed, ensure_ascii=False, indent=2)
    args.ts.write_text(
        f"// generated by vo_build.py from {args.picks.name}, do not edit\n"
        "export type VoWord = { text: string; start: number; end: number }\n"
        "export type VoLine = { id: string; text: string; file: string; duration: number; wordCount: number; "
        "wpm: number | null; pace: string; words: VoWord[] }\n\n"
        f"export const {args.ts_name}: Record<string, VoLine> = {body}\n"
    )
    print(f"wrote {args.ts}")


def _number(value: float | None, digits: int = 1) -> str:
    return "-" if value is None else f"{value:.{digits}f}"


def print_table(lines: list[dict], summary: dict) -> None:
    print(f"\n{'line':<8}{'dur s':>7}{'exp s':>7}{'words':>6}{'wpm':>6}{'w/s':>6}{'syl/s':>6}{'in LUFS':>9}{'out':>7}{'TP':>6}  pace            text")
    for line in lines:
        loud = line["loudness"]
        print(f"{line['id']:<8}{line['duration']:>7.2f}{_number(line['expectedDuration'], 2):>7}{line['wordCount']:>6}"
              f"{_number(line['wpm'], 0):>6}{_number(line['wordsPerSecond'], 2):>6}{_number(line['syllablesPerSecond'], 2):>6}"
              f"{_number(loud['input_lufs']):>9}{_number(loud['output_lufs']):>7}{_number(loud['output_true_peak']):>6}  "
              f"{line['pace']:<16}{line['text']}")
        for note in line["cuts"]:
            print(f"{'':<8}cut {note}")
    print(f"\nloudness: target {summary['target_lufs']} LUFS, output spread {summary['output_spread_lu']} LU, "
          f"max true peak {summary['max_true_peak']} dBTP, input median {summary['input_median_lufs']} LUFS")
    for line_id in summary["quiet_at_source"]:
        print(f"  WARN {line_id}: started 4+ LU below the median: quiet at source, consider re-recording")
